kursach/warehouse/config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/index'
  get 'home/barcode'
  get 'home/product'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

kursach/warehouse/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

kursach/warehouse/app/models/bar_code_company.rb
class BarCodeCompany < ApplicationRecord
end

kursach/warehouse/app/models/bar_code_country.rb
class BarCodeCountry < ApplicationRecord
end

kursach/warehouse/app/models/bar_code_product.rb
class BarCodeProduct < ApplicationRecord
end

kursach/warehouse/app/models/product.rb
class Product < ApplicationRecord
end

kursach/warehouse/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #validates :name
  #validates :rights
  #validates :iduser, presence: true, uiqueness: true
end

kursach/warehouse/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user  
  before_action :require_auto, only: [:index]
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def require_auto
    current_user
    redirect_to login_path unless @current_user
  end
end

kursach/warehouse/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def barcode
  end

  def product
  end
end

kursach/warehouse/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end  
  
  def create
    user = User.find_by_iduser(params[:iduser])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_index_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Id or password is invalid"
      render "new"
    end
  end  
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

kursach/warehouse/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :surname, :patronymic, :iduser, :rights, :password, :password_confirmation)
    end
end

kursach/warehouse/app/helpers/application_helper.rb
module ApplicationHelper
end

kursach/warehouse/app/helpers/home_helper.rb
module HomeHelper
end

kursach/warehouse/app/helpers/sessions_helper.rb
module SessionsHelper
end

kursach/warehouse/app/helpers/users_helper.rb
module UsersHelper
end

kursach/warehouse/app/views/home/barcode.html.erb
<head>
  <title>Werahouse</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">
    *{
      padding: 0;
      margin: 0;
    }
    body {
      padding: 0;
      margin: 0;
    }
    header{
      padding: 18px;
      margin-bottom: 50px;
      color: white;
      background-color: #0405509c;
      min-height: 30px;
      font-size: 24px;
    }
    p {
      font-size: 24px;
      background: rgba(255, 255, 255, 0.3);
      text-align: left;
      padding: 20px 0;
    }
    table{
      margin: 0 auto;
      min-width: 50vw;
    }
    td{
      border: 2px solid;
    }
    #left-header{
      background-color: #04055000;
      padding: 0;
      float: left;
    }
    #right-header{
      background-color: #04055000;
      padding: 0;
      float: right;
    }
    a.link-logout{
      color: white;
    }
  </style>
</head>


<header>
  <p id="left-header">
    <%= User.where(:iduser =>current_user.iduser).first.name %>
    <%= User.where(:iduser =>current_user.iduser).first.surname %>
    <%= User.where(:iduser =>current_user.iduser).first.patronymic %>
  </p>
  <p id="right-header">
    <%= link_to "Log Out", logout_path, class: "link-logout" %>
  </p>
</header>

<div id="country-tables">
  <table>
    <% BarCodeCountry.all.each do |country| %>
      <tr>
        <td>Code: <%= country.code_c %></td>
        <td>Title: <%= country.title%></td>
      </tr>
    <% end %>
  </table>
  <table>
    <% BarCodeCompany.all.each do |company| %>
      <tr>
        <td>Code: <%= company.code_co %></td>
        <td>Title: <%= company.title%></td>
      </tr>
    <% end %>
  <table>
    <% BarCodeProduct.all.each do |product| %>
      <tr>
        <td>Code: <%= product.code_p %></td>
        <td>Title: <%= product.title%></td>
      </tr>
    <% end %>
</div>

kursach/warehouse/app/views/home/index.html.erb
<head>
  <title>Breddit</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">
    *{
      padding: 0;
      margin: 0;
    }
    body {
      padding: 0;
      margin: 0;
    }
    header{
      padding: 18px;
      margin-bottom: 50px;
      color: white;
      background-color: #0405509c;
      min-height: 30px;
      font-size: 24px;
    }
    p {
      font-size: 24px;
      background: rgba(255, 255, 255, 0.3);
      text-align: left;
      padding: 20px 0;
    }
  </style>
</head>


<header>
    Logged in as <%= current_user.name %>
    <%= link_to "Log Out", logout_path %>
</header>

<div>
  <% User.all.each do |user| %>
    <tr>
      <td>Name: <%= user.name %></td>
      <td>Surname: <%= user.surname%></td>
      <td>Patronymic: <%= user.patronymic %></td>
      <td>Rights: <%= user.rights %></td>
      <td>Id user<%= user.iduser %></td>
    </tr>
  <% end %>

</div>

kursach/warehouse/app/views/home/product.html.erb
<head>
  <title>Werahouse</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">
    *{
      padding: 0;
      margin: 0;
    }
    body {
      padding: 0;
      margin: 0;
    }
    header{
      padding: 18px;
      margin-bottom: 50px;
      color: white;
      background-color: #0405509c;
      min-height: 30px;
      font-size: 24px;
    }
    p {
      font-size: 24px;
      background: rgba(255, 255, 255, 0.3);
      text-align: left;
      padding: 20px 0;
    }
    table{
      margin: 0 auto;
      min-width: 50vw;
    }
    td{
      border: 2px solid;
    }
    #left-header{
      background-color: #04055000;
      padding: 0;
      float: left;
    }
    #right-header{
      background-color: #04055000;
      padding: 0;
      float: right;
    }
    a.link-logout{
      color: white;
    }
  </style>
</head>


<header>
  <p id="left-header">
    <%= User.where(:iduser =>current_user.iduser).first.name %>
    <%= User.where(:iduser =>current_user.iduser).first.surname %>
    <%= User.where(:iduser =>current_user.iduser).first.patronymic %>
  </p>
  <p id="right-header">
    <%= link_to "Log Out", logout_path, class: "link-logout" %>
  </p>
</header>

<div id="user-tables">
  <table>
    <% Product.all.each do |product| %>
      <tr>
        <td>Title: <%= product.title%></td>
        <td>Barcode: <%= product.barcode%></td>
        <td>Massa: <%= product.massa%></td>
        <td>Production date: <%= product.production%></td>
        <td>Expiration date: <%= product.expiration%></td>
      </tr>
    <% end %>
  </table>
</div>

kursach/warehouse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kursach/warehouse/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :patronymic %>
    <%= form.text_field :patronymic %>
  </div>
  
  <div class="field">
    <%= form.label :rights %>
    <%= form.text_field :rights %>
  </div>

  <div class="field">
    <%= form.label :iduser %>
    <%= form.text_field :iduser %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

kursach/warehouse/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

kursach/warehouse/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Iduser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.iduser %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

kursach/warehouse/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

kursach/warehouse/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @user.iduser %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>